# Generated by Django 5.1.5 on 2025-01-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_rename_submitted_at_servicerequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('Gas Leak', 'Gas Leak'), ('Meter Issue', 'Meter Issue'), ('Billing Issue', 'Billing Issue'), ('Service Disruption', 'Service Disruption'), ('General Enquiry', 'General Enquiry')], default='General Enquiry', max_length=30),
        ),
    ]
