# Generated by Django 5.1.5 on 2025-01-19 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_servicerequest_resolved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status'], name='customer_se_status_e1b555_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['request_type'], name='customer_se_request_6d3052_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['created_at'], name='customer_se_created_6812e6_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['user'], name='customer_se_user_id_bfab0d_idx'),
        ),
    ]
